Feat/picker
yourssu/YDS-React pull request #14
Opened 2023-10-17 11:28 UTC by HyunsDev

## 1️⃣ 어떤 작업을 했나요? (Summary)

### 기존 코드에 영향을 미치지 않는 변경사항

* `useDOMRef` 훅 추가

* `useUncontrolledValue()` 훅 추가

* `<Picker>` 컴포넌트 추가

## 2️⃣ 알아두시면 좋아요!

`<Picker>` 컴포넌트의 구현이 조금 복잡하게 되어 있어요. 주석의 개선이나 코드를 조금 더 깔끔하게 할 수 있는 방법이 있다면 알려주세요!

## 3️⃣ 추후 작업

-

## 4️⃣ 체크리스트 (Checklist)

- [x ] `main` 브랜치의 최신 코드를 `pull` 받았나요?

2023-10-19 08:35 UTC, nijuy approved these changes
👍 고생하셨습니다!! 리뷰가 쪼끔 늦었죠 호호... 코드도 읽어보고 스토리북으로 이것저것 해보는데 다 잘돼서 넘우 신기했습니다 이런 걸 다 고려하다니 증말 세심하군요 현스...... 궁금한 점이랑 수정 필요한 부분 코멘트 달아놨어요!!!

2023-10-19 08:35 UTC, nijuy commented on src/components/Picker/Picker.style.ts
> +import styled from 'styled-components';
라인 1에서 중괄호를 안 쓰면 eslint 관련 경고가 떠서 (사진), 저는 그동안 style.ts 파일에서 중괄호를 계속 썼었거든요!

![image](https://github.com/yourssu/YDS-React/assets/87255462/7a5aa82f-e653-4648-a12f-69c21fdd854e)

따로 룰 추가하거나 (`'import/no-named-as-default': 'off',`) 중괄호 사용하는 방식으로 통일하면 어떨까 싶은데 현스 생각은 어떤가요? 넘 사소한 부분인거 같긴 하지만 일단 코멘트 남겨봅니당 ^ㅅ^

2023-10-19 08:35 UTC, nijuy commented on src/components/Picker/Picker.tsx
> +import { StyledPicker } from './Picker.style';
혹시 eslint import/order 적용이 잘 되고 있나요? `feat/picker` 브랜치를 에디터에서 여니까 빨간줄이...🥺 `PickerColumn` 에서도 동일한 문제가 있던데 확인 부탁드립니다~!

|현재|import/order rule 적용했을 때|
|---|---|
|![image](https://github.com/yourssu/YDS-React/assets/87255462/549d9601-a7d3-4570-a742-b54af026c622)|![image](https://github.com/yourssu/YDS-React/assets/87255462/3f2472f1-2334-43f2-9b49-24c4f1259a61)|
|![image](https://github.com/yourssu/YDS-React/assets/87255462/d1874211-c3fa-4d0d-852b-d93c4b0d3d38)|![image](https://github.com/yourssu/YDS-React/assets/87255462/5498568e-b47d-4093-a993-e1e2fe579021)|

2023-10-19 08:35 UTC, nijuy commented on src/components/Picker/PickerColumn.tsx
> +      }, 100);
여기서 `ignoreChangeTimer`를 사용했을 때 장점이 궁금해요!! `useRef`는 html element에 달아서 쓰는 것만 해봤는데 이렇게 쓰는 걸 처음 봐서 짱신기 👀👏

2023-10-20 12:55 UTC, Hanna922 requested changes

2023-10-20 12:55 UTC, Hanna922 commented on src/components/Picker/PickerColumn.tsx
> +    }, [value]);
여기랑 98번 라인 및 hooks 파일에서 useEffect dependency 부분에 eslint 경고가 발생하고 있네용 확인 부탁드려요!

2023-10-20 12:55 UTC, Hanna922 commented on src/components/Picker/Picker.tsx
> +export const Picker = forwardRef<HTMLDivElement, PickerProps>(({ children, ...props }, ref) => {
Picker 한 개당 최대 3개의 PickerColumn을 가질 수 있다는 제한 사항이 있어서 갯수 제한을 설정해주시면 더 좋을 것 같아요!

2023-10-20 12:55 UTC, Hanna922 commented on src/components/Picker/PickerColumn.tsx
> +    const onTouchStart = () => {
궁금한 부분이 있어요!
요렇게 모바일 터치 지원 코드를 작성하지 않을 경우 모바일에서 클릭이나 드래그 시 문제가 발생하는 건가요??

2023-10-20 12:55 UTC, Hanna922 commented on src/components/index.ts
> +export type { PickerProps, PickerColumnProps } from './Picker';
@nijuy 요기 Toggle이 빠진걸 확인했어요! 핳ㅎㅎㅎ

2023-10-20 12:55 UTC, Hanna922 commented on src/components/Picker/Picker.tsx
> +Picker.displayName = 'Picker';
저는 이 코드를 작성하지 않았어서 그런데, 혹시 해당 코드의 역할이 어떤 건가용??
필요하면 저도 추가하려구요!!

2023-10-20 13:15 UTC, HyunsDev commented on src/components/Picker/Picker.style.ts
> +import styled from 'styled-components';
앗 확인했습니다. 해당 이슈 수정할 때 린트도 함께 추가할께요!

2023-10-20 13:16 UTC, HyunsDev commented on src/components/Picker/Picker.tsx
> +import { StyledPicker } from './Picker.style';
으잉 확인해보겠습니다!

2023-10-20 13:24 UTC, HyunsDev commented on src/components/Picker/PickerColumn.tsx
> +    const onTouchStart = () => {
Picker의 드래그 기능의 동작 원리는 스크롤바를 하나 만들고, 스크롤이 멈추면 일정 시간 뒤에 해당 위치에 있는 값을 사용하는 방식이에요. 이를 구현하기 위해서는 터치, 드래그가 끝나는 시점을 알아야해요. Picker에서는 요소를 클릭하는 것외에 3가지 상황을 고려했어요.

1. 마우스휠을 이용한 방법(또는 터치패드)
onScroll 이벤트 리스너를 통해 스크롤박스의 스크롤을 감지하고, 100ms 이상 변화가 없으면 선택한 걸로 간주하여 선택해요

2. 마우스 드래그를 이용한 방법
onMouseDown, onMouseMove, onMouseUp, onMouseLeave를 이용하여 마우스를 클릭하고 마우스 버튼을 땐(또는 leave한) 11시점을 감지하여 선택해요

3. 모바일 터치를 이용한 방법
모바일 터치는 마우스휠을 이용한 방법과 비슷하지만, 모바일은 손이 클릭하고 있다는 것을 알 수 있으므로(onTouchStart, onTouchEnd) 100ms 이상 변화가 없을 때 선택한거라고 간주할 필요가 없어요. 따라서 해당 코드를 추가했어요.

2023-10-20 13:27 UTC, HyunsDev commented on src/components/Picker/PickerColumn.tsx
> +      }, 100);
스크롤을 통해 항목을 선택할 때 타이머를 달아서 100ms 이상 스크롤 값에 변화가 없으면 해당 위치에 있는 항목을 선택하는 방식이에요.

따라서 100ms 안에 변화가 발생하면 타이머를 취소해야 되기 때문에 이와 같은 코드를 작성했어요.

2023-10-20 13:28 UTC, HyunsDev commented on src/components/index.ts
> +export type { PickerProps, PickerColumnProps } from './Picker';
앗 Toggle 마지되기 전에 올린 PR이라 추가를 못했어요. 나중에 이슈 수정할 때 함께 해결할게요

2023-10-20 14:00 UTC, nijuy commented on src/components/index.ts
> +export type { PickerProps, PickerColumnProps } from './Picker';
@Hanna922 저 그동안 여기를 계속 놓치고 있었더라고요 뱃지도 한나가 추가해줬던거 이제야 발견 ^^••••

@HyunsDev 제가 Toast 작업하면서 은근슬쩍 끼워넣을게요~!

2023-10-20 14:01 UTC, nijuy commented on src/components/Picker/Picker.tsx
> +Picker.displayName = 'Picker';
헉 이거 디버깅때문에 추가해야 한다고 했던 거 같아요!! [YDS Web - 개발 가이드쪽 보면 관련 문서](https://www.notion.so/yourssu/b5b065c12d4640d485127443bea486d1?pvs=4) 있을거에요 저도 토글에 추가하겠웁니다 🥺 ➡ #16

2023-11-20 15:42 UTC, HyunsDev commented on src/components/Picker/Picker.tsx
> +export const Picker = forwardRef<HTMLDivElement, PickerProps>(({ children, ...props }, ref) => {
이 부분은 디자인적으로만 고려해도 충분할 것 같고, 추후 확장 가능성을 위해 의도적으로 추가하지 않았어요.

갯수 제한을 걸려면 context로 컴포넌트의 수를 센 다음에 3개 초과면 오류를 던저야 하는데, 이 정도의 오버헤드를 감수하면서 개발 단에서 제한을 추가할 필요는 없을 것 같습니다.

2023-11-21 13:48 UTC, nijuy approved these changes

2023-11-21 13:49 UTC, Hanna922 approved these changes

2023-11-21 13:49 UTC, merged