feat: BoxButton 구현
yourssu/YDS-React pull request #5
Opened 2023-09-14 11:28 UTC by Hanna922

## 1️⃣ 어떤 작업을 했나요? (Summary)
- BoxButton 구현했습니다

## 2️⃣ 알아두시면 좋아요!
BoxButton.style.ts 쪽에서 prop를 넘길 때 타입 설정을
```
$types: styledBoxButtonProps['$types'],
$theme: styledBoxButtonProps['$theme']
```
다음과 같은 형태로 해두었는데, 혹시 더 좋은 방법 아시는 분 계실까요,,,,?

2023-09-15 08:26 UTC, HyunsDev requested changes

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +export type size = 'small' | 'medium' | 'large' | 'extraLarge';
1. 타입명의 첫 글자는 **대문자로 작성**해주세요.
2. 해당 타입들도 export가 되므로 다른 타입명과 충돌되지 않도록 `BoxButtonSize`  형태로 작성해주세요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +interface styledBoxButtonProps {
interface 명의 첫 글자는 대문자로 작성해주세요

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +export interface Props extends BoxButtonProps {
BoxButtonProps가 있는데 해당 속성에 아래 3개 속성을 추가하지 않고 추가하신 이유가 있을까요?

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +export interface Props extends BoxButtonProps {
이 경우 leftIcon, title, rightIcon 속성이 제대로 외부에 노출되지 않아서 문제가 발생할 것 같습니다.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +  title: string;
버튼 내부에 들어가는 텍스트를 의도하신 것 같은데, `title` 대신 `children`, `string` 타입 대신 `React.ReactNode` 타입을 사용해주세요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +        {title}
3가지 컴포넌트를 함께 사용할 경우 아이콘 사이 간격에서 문제가 발생할 가능성이 높아요. Ieft, Right Icon, title을 span 태그로 감싸는 것도 고려해주세요

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +const getSizeStyle = ($size: styledBoxButtonProps['$size']) => {
웹에서 사용되는 버튼의 경우 width를 특정 너비로 고정하지 말고 `100%`, `fit-content`, 커스텀 너비(100px) 등 여러 선택지를 제공해야 돼요. 모바일 환경 전용이더라도 대부분 100%로 설정하는 것이 좋습니다.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
혹시 title의 길이가 길어져서 warp가 되는 상황을 고려하셨나요? 물론 버튼에 긴 텍스트를 넣는 것이 좋은 상황은 아니지만 해당 상황을 고려할 필요는 충분하다고 생각해요.

CSS 속성 중 `text-overflow: ellipsis;` 를 고려해보시면 좋을 것 같아요. 
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.stories.tsx
> +    title: {
Storybook은 기본적으로 argTypes를 자동으로 작성하므로 스토리북에서는 작성하지 않는 편이 좋을 것 같아요!
나중에 Props가 변경되었을 때 수정해야 하는 부분이 늘어서 실수할 가능성이 증가할 것 같습니다.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +  isDisabled: isDisabled;
disabled 같은 경우 html button 속성 중에 `disabled` 라는 속성이 있어요. 추후 react-hook-form 과 같은 라이브러리와의 호환성을 위해 이미 html에 존재하는 속성이 있다면 해당 속성을 사용해주세요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +} & React.ButtonHTMLAttributes<HTMLButtonElement>;
ButtonHTMLAttributes 라는 타입을 사용해도 좋지만, 되도록 이미 존재하는 HTML 태그의 타입을 가져올 때는 `ComponentProps`, `ComponentPropsWithRef` 타입을 사용해주세요. 두 타입이 아닌 다른 타입은 실제 사용시 일부 속성이 누락되는 경우가 있을 수 있어요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +export type types = 'filled' | 'tinted' | 'line';
속성 명에 복수형을 사용하는 것은 자칫 Array 형으로 착각할 수 있어서 변경해야 될 것 같아요. `type`으로 변경하면 좋겠지만, 이미 html 속성 중 type이 있으므로 variant 라는 이름을 추천드려요!

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
Button이라는 컴포넌트 명은 자칫 혼란을 이르킬 수 있을 것 같아요. 저 같은 경우는 Styled 컴포넌트 이름을 정할 때 앞에 prefix로 "Styled"를 붙여요. 이 방법대로라면 `Button` 컴포넌트는 `StyledBoxButton` 라고 바꿀 수 있겠네요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
위에서 `styledBoxButtonProps` 라는 속성을 정의했지만 이곳에서는 적용되지 않았어요. $로 시작되지 않는 속성이 전달되는 경우 DOM 트리가 오염되어서 일부 라이브러리(vite, Next.js)에서 경고를 띄워요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +export type theme = YDSTheme;
테마를 컴포넌트를 사용할 때 따로 넘겨주는 건 불필요한 것 같아요. 만약 styled가 아닌 일반 컴포넌트 내에서 theme를 가져와야 한다면 해당 컴포넌트에서 useTheme() 훅을 사용해 가져와주세요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +  ({ leftIcon, title, rightIcon, ...props }, ref) => {
Button에 사용되는 타입들이 있지만 기본 값이 추가되지 않은 것 같아요. 매번 버튼을 사용할 때마다 값을 지정하는 것은 비효율적이라고 생각하는지라 자주 사용하는 값을 기본 값으로 추가하는 게 좋을 것 같아요.

ex. `{ leftIcon, title, rightIcon, size = 'medium', rounding = 4, ...props }`

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +  $types: styledBoxButtonProps['$types'],
`styledBoxButtonProps['$types']` 도 큰 문제는 없어 보이지만 이왕이면 `styledBoxButtonProps['$types']`의 원래 타입인 `types` 로 작성하는 것도 좋은 것 같아요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +  $theme: styledBoxButtonProps['$theme']
혹시 `$theme`를 외부에서 가져오는 이유가 있으신가요? css`` 를 사용하신다면 `${props => props.theme}` 형태로 가져올 수 있는 것으로 알고 있어요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
css에 `transition` 속성을 추가하는 건 어떠신가요? hover 했을 때 색이 바로 바뀌는 것보다는 자연스러울 것 같아요. 저는 주로 `transition: 150ms` 옵션을 즐겨 사용합니다!

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +export type isDisabled = boolean;
isDisabled, isWarned 같은 타입까지 타입 별칭을 사용할 필요는 없을 것 같아요. size, rounding, types 처럼 string, number가 아닌 특정한 값을 가지는 타입에만 별칭을 붙이는 게 좋을 것 같습니다!

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.type.ts
> +export type BoxButtonProps = {
타입 별칭(type) 보다는 인터페이스(interface)를 사용하는 편이 조금 더 좋을 것 같은데 어떻게 생각하시나요?

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.stories.tsx
> +const meta: Meta<typeof BoxButton> = {
`layout: "centered` 속성을 추가하면 조금 더 예쁜 스토리 화면을 볼 수 있어요!

```
parameter: {
    layout: "centered"
}
```

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.tsx
> +        {leftIcon}
주로 leftIcon과 rightIcon에는 아이콘 컴포넌트가 많이 들어갈 것 같은데, 이 경우 IconContext.Provider 사용해주시면 추후 사용할 때 아이콘을 사용할 때마다 사이즈와 색을 조절해야 하는 수고를 줄일 수 있어요.

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +  switch ($types) {
switch 문을 사용하는 것도 좋지만 Object를 사용하는 방식도 좋을 것 같아요.

```ts
const NormalStyleMap: Record<styledBoxButtonProps['$types'], RuleSet<object> = {
    filled: css``,
    tinted: css ``,
    line: css``,
}
```

2023-09-15 08:26 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +const getSizeStyle = ($size: styledBoxButtonProps['$size']) => {
만약 추후 width를 가변으로 변경할 경우 padding를 사용해서 글자와 외곽선 사이 간격이 너무 없지 않게 해주세요!

2023-09-18 04:13 UTC, nijuy commented on src/components/BoxButton/BoxButton.stories.tsx
> +const meta: Meta<typeof BoxButton> = {
오. 저도 스토리 작성할 때 참고했어요 감삼다 ^ㅅ^

2023-09-18 04:22 UTC, nijuy commented on src/components/BoxButton/BoxButton.style.ts
> +  gap: 4px;
제가 맡은 `Badge`도 아이콘 오른쪽으로 margin을 줘야 해서 아이콘 쪽을 건드려야 하나 싶었는데, 이거 보고 저도 일단 한나처럼 `gap: 4px`로 줘놨어요..!! 😂

2023-09-18 10:44 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
반영하겠습니다!

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +  switch ($types) {
혹시 switch 문에 비해 이점이 있을까요?? 개인적으로 switch 문이 더 가독성이 좋은 것 같아서용

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +const getSizeStyle = ($size: styledBoxButtonProps['$size']) => {
해당 부분 디자인이 전부 픽셀로 고정되어 있는 상태라 이렇게 해둔건데ㅠ 지금으로써 100%로 무조건 지정하는게 맞을지 고민되네요

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
피그마 디자인 및 이전 레포 참고 시 하나만 정의되어 있더라구요..? 이 부분은 디자인 팀과 논의 후 추가해야 할 것 같아요!

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.tsx
> +        {title}
어떤 문제 말씀하시는 걸까요??

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.tsx
> +  title: string;
string 대신 React.ReactNode를 사용하는 이유가 어떤 건가요?? string보다 더 넓은 범위를 갖는 타입인데, 버튼 내부에 들어가는 텍스트라면 string이 더 적합하지 않나용?

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.tsx
> +  ({ leftIcon, title, rightIcon, ...props }, ref) => {
기본 값은 그냥 저희가 임의로 정하는 걸까요,,?

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.type.ts
> +export type types = 'filled' | 'tinted' | 'line';
엇 피그마 상 type으로 되어 있는데 type으로 변경하면 문제가 발생할까요?

2023-09-18 10:51 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.type.ts
> +export type BoxButtonProps = {
interface로 변경하겠습니다!

2023-09-19 01:13 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.type.ts
> +} & React.ButtonHTMLAttributes<HTMLButtonElement>;
해당 부분 잘 이해가 안되어서 그런데, ButtonHTMLAttributes 사용 시 일부 속성이 누락되는 경우가 어떤 현상인가요??

2023-09-19 01:16 UTC, EATSTEAK commented on src/components/BoxButton/BoxButton.tsx
> +  title: string;
보통 Button같은 컴포넌트를 사용할 때 내부에 들어가는 타이틀의 경우 이런 식으로 작성하시는 게 익숙하실 거에요:
```html
<Button>텍스트</Button>
```

하지만 작성하신 것처럼 `title` attribute 로 구현한다면

```html
<Button title='텍스트' />
```
요런 식으로 작성하게 되겠죠?

저는 태그를 보조해주는 요소의 값들은 attribute 를 이용하는 것이 맞다고 생각하지만, 태그 내부의 주 content의 경우 태그 내부에 작성하는게 맞다고 생각하거든요.

첫번째 예시처럼 컴포넌트의 구조를 변경하려면 React 에서 제공하는 `children` 프로퍼티를 이용해야 하고, 해당 프로퍼티의 타입은 `React.Node` 로 고정되어 있으니 이를 이용하는게 나아 보여요.

2023-09-19 01:22 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.tsx
> +  title: string;
@EATSTEAK 오,, 바로 이해되었어요🥹 감사합니다!!👍🏻👍🏻

2023-09-19 03:18 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +  switch ($types) {
이 부분은 취향 차이라서 Hanna님이 원하시는 방식대로 하시면 될 것 같아요. 저도 두 가지 방법 모두 혼용해서 사용하고요!

2023-09-19 03:23 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +const getSizeStyle = ($size: styledBoxButtonProps['$size']) => {
기본적으로는 fit-content로 하고, 필요에 따라 width를 조정할 수 있도록 width Prop을 추가하는게 맞을 것 같아요.

<img width="248" alt="image" src="https://github.com/yourssu/YDS-React/assets/46562466/5b449754-19e5-485d-9e5b-a708022a2e4f">

<img width="320" alt="image" src="https://github.com/yourssu/YDS-React/assets/46562466/59352f32-0c87-47c7-bd4a-5c1b19707bf8">

디자인 상 width가 특정 px로 고정되어 있지만, 디자인 단계에서 가변 너비를 고려한 것을 볼 수 있어요. 이런 부분을 고려했을 때 가변 너비로 설정해야 될 것 같아요.

2023-09-19 03:25 UTC, HyunsDev commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
참고로 text-overflow는 display:block에서만 동작하는지라 생각보다 까다로워요.아래 코드는 제가 Button을 개발했을 때 사용한 코드인데 필요한 경우 참고해보셔도 좋을 것 같아요.

https://design.opize.me/?path=/story/html-like-component-button--primary
https://github.com/HyunsDev/opize-design-system/blob/main/src/components/Button/Button.style.tsx

2023-09-19 03:36 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +const getSizeStyle = ($size: styledBoxButtonProps['$size']) => {
컴포넌트의 사이즈 별로 width가 정해져있는 디자인인데도 width를 props로 넘기는게 적절한 건가요?? 이 부분 회의에서 더 얘기 나눠보고 싶어용

2023-09-19 03:39 UTC, Hanna922 commented on src/components/BoxButton/BoxButton.style.ts
> +export const Button = styled.button<BoxButtonProps>`
엇 혹시 해당 코드 파일의 어떤 부분을 참고하면 되는 걸까요..? 그런데 지금 다시 생각해보면 BoxButton에 긴 텍스트가 들어갈 상황이 발생하지 않을 것 같기도 하네요 이 부분도 오늘 얘기해볼 수 있을까요??

2023-09-27 03:46 UTC, Hanna922 commented
@HyunsDev @nijuy 변경사항 확인 부탁드려요!

2023-09-27 08:36 UTC, nijuy approved these changes

2023-09-27 08:52 UTC, merged