feat: CheckBox 구현
yourssu/YDS-React pull request #9
Opened 2023-10-03 15:28 UTC by Hanna922

## 1️⃣ 어떤 작업을 했나요? (Summary)
- CheckBox 구현했습니다.

## 2️⃣ 알아두시면 좋아요!
handleWrapperClick 쪽에서 isDisabled일 경우 return, 아닐 경우 checked 값에 따라 isSelected 변경되도록 구현해두었습니다. 혹시 더 좋은 방법이 있다면 알려주세요!

## 3️⃣ 추후 작업
PlainButton 이어서 작업할게용

2023-10-04 13:37 UTC, nijuy reviewed
고생하셨습니다!! 열일한나... ( •̀ ω •́ )✧👍 궁금한 점 코멘트로 남겨두겠습니당

2023-10-04 13:37 UTC, nijuy commented on src/components/CheckBox/CheckBox.stories.tsx
> +  title: 'Component/CheckBox',
저는 [Badge](https://github.com/yourssu/YDS-React/pull/6/files#diff-0532698a6747ca92ee2fd82d5478b60589d49ecec9b765d6364b9badf6ef1803) 제작하면서 스토리 타이틀의 분류는 피그마/노션을 따라서 `Atoms/Badge`로 했었는데요! CheckBox와 BoxButton은 폴더 구조를 따라서 `Component/xx`로 되어 있는 거 같아요! 맞나요?

3개 다 아톰이라 같은 분류에 있는 게 맞는 거 같아서 코멘트 남깁니당 ㅎㅅㅎ
제가 Badge를 Component로 옮기거나, 한나의 CheckBox와 BoxButton을 Atoms 하위로 옮기거나 해야 할 거 같아요! 

제가 이걸 BoxButton때 물어봤어야 했는데!! 아!!!!

2023-10-04 13:41 UTC, nijuy commented
스토리북 Controls 탭에서 `isDisabled`는 잘 되는데 `isSelected`는 안 되는 거 같아요!
케이스별 스토리를 만들어 두셔서 확인은 전부 했는데 궁금해서 물어봅니당

(움짤은 controls 탭에서 `isDisabled` 제어 잘 되는 거 확인 ➡ 클릭했을 때 `isSelected` 제어 되는 거 확인 ➡ controls 탭에서 `isSelected` 값을 바꾸고 있는데 변화가 없는 점 순서로 녹화했습니다)
![homehome](https://github.com/yourssu/YDS-React/assets/87255462/1d6dc369-6c1d-4ec9-b2db-eacc1756bed1)

2023-10-04 14:01 UTC, Hanna922 commented
@nijuy 엇 이 부분 다시 보시면 클릭했을 때 isSelected 제어 안되는 거 확인하실 수 있어요! 여기 부분은 State가 실시간으로 반영되지 않아서 이렇게 보이는 것 같아서 다른 방법이 있을지 모르겠네요ㅜ 이전 YDS 레포에서도 클릭이 가능하도록 만들어둔 Toggle 같은 경우에는 isSelected 제어를 실시간으로 하지 않더라구요!

2023-10-04 14:03 UTC, Hanna922 commented on src/components/CheckBox/CheckBox.stories.tsx
> +  title: 'Component/CheckBox',
저도 Atoms로 분류하는게 맞을 것 같아요!!
근데 BoxButton, CheckBox, PlainButton 전부 Component로 해둔 상태라 요건 따로 브랜치 파서 한 번에 작업 할게요 ㅎㅅㅎ...!

2023-10-04 14:19 UTC, nijuy commented
> @nijuy 엇 이 부분 다시 보시면 CheckBox 직접 클릭했을 때 isSelected 제어 안되는 거 확인하실 수 있어요! 여기 부분은 State가 실시간으로 반영되지 않아서 이렇게 보이는 것 같은데 다른 방법이 있을지 모르겠네요 ㅠㅡㅠ... 이전 YDS 레포에서도 클릭이 가능하도록 만들어둔 Toggle 같은 경우에는 isSelected 제어를 실시간으로 하지 않더라구요! 근데 녹화해주신거 너무 최고에욥...

앟. 직접 클릭했을 때는 상태가 잘 변하는데 controls 탭에서 `isSelected`를 바꾸면 상태가 안 변한다! 라는 얘기였습니다
제가 이상하게 적었군요..... ٩( *˙0˙*)۶

저번에 알려주셨던 [예전 배포판(?)](https://yds-react.yourssu.com/?path=/story/example-introduction--page) 보니까 checkbox는 실시간 제어가 되는데 한나 말대로 toggle은 안되네요 멋쓱 !

2023-10-04 14:24 UTC, Hanna922 commented
@nijuy 그 예전 배포판에서 Checkbox가 isSelected로 제어가 되는 이유가 CheckBox 자체를 클릭할 수 있는 기능을 지원하지 않아서 그런 걸거에요! 클릭이 안되더라구욥 큐ㅠㅠㅠ
반면 토글이 안되는 이유는 제가 구현한 CheckBox처럼 클릭을 지원해서 그렇지 않을까 생각합니당

2023-10-04 14:41 UTC, Hanna922 commented on src/components/CheckBox/CheckBox.stories.tsx
> +  title: 'Component/CheckBox',
요거 여기서 변경했습니당!!

2023-10-05 09:22 UTC, nijuy approved these changes

2023-10-05 10:41 UTC, HyunsDev requested changes

2023-10-05 10:41 UTC, HyunsDev commented on src/components/CheckBox/CheckBox.tsx
> +    const [isSelected, setIsSelected] = useState(propIsSelected);
isSelected 상태는 useState 를 사용하지 말고, 컨트롤되지 않는 속성 (ref 이용)해서 작성해주세요.

useState를 이용할 경우 react-hook-form 등의 라이브러리에서 문제가 발생하거나, 불필요한 코드가 증가할 수 있어요.

2023-10-05 10:41 UTC, HyunsDev commented on src/components/CheckBox/CheckBox.tsx
> +    const [isSelected, setIsSelected] = useState(propIsSelected);
만약 스타일링 때문이라면 React에서 스타일을 관리하지 않고, css에서 스타일을 관리하는 방안도 확인해주세요! 아래 형태로 작성할 경우 checked 상태에 따라 스타일을 변경할 수 있어요.

```css
&:checked {
    ...
}
```

2023-10-05 10:41 UTC, HyunsDev commented on src/components/CheckBox/CheckBox.tsx
> +    const handleWrapperClick = () => {
onClick이 상태 변경으로만 한정되어 있는데, 추가적인 onClick이 필요한 경우도 있을 것 같아요. (체크와 함께 Toast 표시 등)

외부 props로 onClick을 받아서 

```tsx
const handleWrapperClick = () => {
    if (props.onClick) props.onClick();
    if (isDisabled) return;
    if (inputRef.current) {
          inputRef.current.checked = !inputRef.current.checked;
          setIsSelected(inputRef.current.checked);
    }
};

2023-10-05 10:45 UTC, HyunsDev requested changes

2023-10-05 10:45 UTC, HyunsDev commented on src/components/CheckBox/CheckBox.style.ts
> +export const StyledCheckBoxWrapper = styled.div<StyledCheckBoxProps>`
버튼 스타일에 `cursor: pointer` 적용해주시겠어요?

2023-10-05 10:56 UTC, HyunsDev commented
<img width="161" alt="image" src="https://github.com/yourssu/YDS-React/assets/46562466/5146e5c8-914b-425e-bcfc-d4d2346b5656">

라벨이 드래그가 되는데, `user-select:none` 으로 드래그를 해제하는게 좋을 것 같아요.

2023-10-10 13:44 UTC, nijuy commented on src/components/CheckBox/CheckBox.style.ts
> +  }
아까 회의에서 한나가 말했던 거요!!!

1) StyledCheckBoxWrapper에 `cursor:pointer` 지정
2) `input:disabled + .label` 에서 `cursor: not-allowed` ➡ 안됨

이거 살펴봤는데 Disabled Story에서 실제로 input이 disabled 된 상태가 아니라서 안 먹힌 거 같아요! 사진 보면 

![image](https://github.com/yourssu/YDS-React/assets/87255462/4d12d711-2543-4a50-b636-2d19e887455b)

2023-10-10 14:51 UTC, nijuy commented
@HyunsDev 
(제가 모바일이라 코드 부분에 코멘트 다는 게 어려워서 ㅠㅠㅋㅋㅋㅋㅋ 요렇게 답니다,,)

👍 div (icon-padding)로 체크와 라벨 사이 여백 넣는 것보다 gap으로 주는 게 깔끔해보여서!! 최고ㅇㅔ요

`useImperativeHandle` 관련 코드는 Toggle에도 추가해야 할 것 같아서 낼 알아보고 수정하겠습니다 👀

2023-10-12 15:33 UTC, merged